- Mail/Views/Bottom sheets/Actions/ActionsViewModel.swift
- Mail/Views/New Message/NewMessageView.swift
- Mail/Views/Search/SearchViewModel.swift
- Mail/Views/Thread List/ThreadListView.swift
- Mail/Views/Thread List/ThreadListViewModel.swift
- MailCore/Cache/BackgroundRealm.swift
- MailCore/Cache/ContactManager.swift
- MailCore/Cache/MailboxManager.swift
- MailCore/Utils/Realm+Extensions.swift
Ensure that writes are done in the background with async continuation.
Starting now, only use `realm.safeWrite` when writing outside the main thread.
> Refactor concurrency

- Mail/Views/Thread List/ThreadListView.swift
Fix spacer no clear color.
The issue was visible only in dark mode.
Fix for empty view comes in an other PR.
> Make spacer transparent

- Mail/Views/Thread List/ThreadListView.swift
Before
After
2476-02cf-4b27-aef1-407834bd8342.png)
> Fix(ThreadListView): ProgressView remove listRowBackground

- Mail/Components/RecipientAutocompletionCell.swift
- Mail/Components/RecipientField.swift
- Mail/Helpers/RichTextEditor.swift
- Mail/Views/New Message/ComposeMessageView.swift
- Mail/Views/New Message/NewMessageCell.swift
Fix hit box areas:
Select "to" field on appear
Fix #349 
Fix #342
> Fix: Hitboxes composeview

- Mail/Views/Thread List/ThreadListHeader.swift
- MailCore/Cache/MailboxManager.swift
Unread count value wasn't updated when a message (from another folder) was added to a thread in the current folder or when an action was performed on a message from another folder in the current folder.
> fix: Update unread count value when updating folder

- Mail/Views/New Message/Attachments/AttachmentUploadCell.swift
- Mail/Views/New Message/Attachments/AttachmentsHeaderView.swift
- Mail/Views/New Message/Attachments/AttachmentsManager.swift
- Mail/Views/Thread/AttachmentCell.swift
- Mail/Views/Thread/AttachmentsView.swift
- Resolve flickering when one attachment was being uploaded
- Prevent too much view redraws only update subviews on progress
- Separate AttachmentCell and AttachmentUploadCell
> fix: Attachment upload progress

- Mail/Views/AlertView.swift
Present alerts fullscreen anywhere.
Present alert from an object binding instead of a Bool.
> refactor: Custom alerts as fullscreen sheet

- Mail/Views/Thread/MessageBodyView.swift
- MailCore/Models/Message.swift
- MailCore/Utils/Constants.swift
- Write a message from Mail.app (macOS)
- Empty Body
- Add an attachment
-> Value and Type are null
> fix(Body): Value and Type can be null

- Mail/AppDelegate.swift
In some cases token was nil when registering for notifications
> fix: Ensure non nil token

- Mail/Views/Switch User/AccountListView.swift
- Mail/Views/Switch User/AccountView.swift
- MailCore/Cache/AccountManager.swift
- Project.swift
- Prevent duplicate account in AccountListView
- Prevent crash adding wrong hash to dictionnary
- Refactor AccountView to stop using SheetState and stop using ObservableObject on account
> fix: Prevent duplicate account in AccountListView

- Mail/Components/CheckboxView.swift
- Mail/Components/IKDivider.swift
- Mail/Components/MailButton.swift
- Mail/Components/MailButtonStyle.swift
- Mail/Components/ThreadCell.swift
- Mail/Components/UnreadIndicatorView.swift
- Mail/LockedAppView.swift
- Mail/Utils/FloatingActionButtonModifier.swift
- Mail/Views/Bottom sheets/MoreStorageView.swift
- Mail/Views/Bottom sheets/ReportDisplayProblemView.swift
- Mail/Views/Bottom sheets/RestoreEmailsView.swift
- Mail/Views/EmptyStateView.swift
- Mail/Views/Menu Drawer/Folders/FolderCell.swift
- Mail/Views/Menu Drawer/Folders/UserFoldersListView.swift
- Mail/Views/Menu Drawer/Items/MenuDrawerItemCell.swift
- Mail/Views/Menu Drawer/Items/MenuDrawerItemsListView.swift
- Mail/Views/Menu Drawer/MailboxManagement/MailboxesManagementButtonView.swift
- Mail/Views/Menu Drawer/MailboxManagement/MailboxesManagementView.swift
- Mail/Views/Menu Drawer/MailboxQuotaView.swift
- Mail/Views/NoMailboxView.swift
- Mail/Views/Onboarding/OnboardingView.swift
- Mail/Views/Onboarding/SlideView.swift
- Mail/Views/Thread List/ThreadListView.swift
- MailCore/UI/UIConstants.swift
- MailCore/Utils/Constants.swift
Some constants could later be moved in Core sush as `mailRegex`
Closes #305
> refactor: move UI constants to UIConstants enum

- Mail/Views/Onboarding/SlideView.swift
> fix: Onboarding freeze

- Mail/Views/Thread/MessageView.swift
- MailCore/Utils/MessageBodyUtils.swift
Preprocessing of the mail is blowing up with large ones.
The preprocessing we do with "swift soup" is blowing up not in a manner I can quickly optimize.
Therefore I used an heuristic to disable preprocessing of emails larger than 5meg.
Works like a charm, email is still displayed resonably well, and some other mail clients use this trick.
“Possibly the most common error of a smart engineer is to optimise a thing that should not exist”  - Musk
> Large complex mails are slow to display

- Mail/Views/Thread/MessageView.swift
- Project.swift
Performance issues on displaying large emails with inline pictures.
The mainthread was pinned, batching image processing greatly improves the UX in my testing.
Mutating the dom of the email is super costly, therefore I used batching to process images and mutate less the content of the email view that is rendered on the main thread.
I went from 300 sec to 50 ish for a mail with a lot of small images, while keeping the UI responsive
> Inline images mail slow to display

- Mail/Components/CheckboxView.swift
- Mail/Components/SelectionBackground.swift
- Mail/Components/ThreadCell.swift
- Mail/Utils/FloatingActionButtonModifier.swift
- Mail/Views/Thread List/ThreadListCell.swift
- Mail/Views/Thread List/ThreadListView.swift
- MailCore/UI/UIConstants.swift
- Remove unnecessary animations
- Improve activation animation for compact and normal densities
- Improve thread cell's hit box
> fix(MultipleSelection): Improve animations

- Mail/Components/SelectionBackground.swift
- MailCore/UI/UIConstants.swift
Currently on iPad the selection background (gray color) and the multiple selection background (pink color) have different vertical padding.
It results in backgrounds with different heights.
> fix: Selection and multiple selection should have the same vertical padding

- Mail/Components/ActionsPanelButton.swift
- Mail/Components/BottomBarView.swift
- Mail/Components/MailButton.swift
- Mail/Components/ToolbarButton.swift
- Mail/Utils/GeometryReaderHelpers.swift
- Mail/Views/Thread List/ThreadListModifiers.swift
- Mail/Views/Thread/MessageHeaderDetailView.swift
- Mail/Views/Thread/ThreadView.swift
- MailCore/UI/UIConstants.swift
We have 5 items on our bottom bar. With a small screen, the layout is broken, so we now use our own component.
> fix: Current toolbar break when the screen is too small

- Mail/Views/Thread/MessageView+Preprocessing.swift
- MailCore/Cache/MailboxManager.swift
- MailCore/Models/Draft.swift
- MailCore/Models/Message.swift
- Project.swift
- Truncate email too long, right now at 10MB.
- Main mail message is compressed with lzfse (zstd like), to reduce presure on realm.
- Core PR with compression helpers https://github.com/Infomaniak/ios-core/pull/43
> feat: truncate email too long for Realm

- .package.resolved
- Mail/Components/BottomBarView.swift
- Mail/Views/Thread List/ThreadListCell.swift
- Mail/Views/Thread List/ThreadListModifiers.swift
- Mail/Views/Thread List/ThreadListMultipleSectionViewModel.swift
We need to ignore the keyboard safe area so it looks nice on iPad.
To do this, we need to use a VStack instead of a safeAreaInset. However, SwiftUI cannot handle well the appearance animation in this situation, so I decided to remove the animation.
> fix(BottomBar): Ignore keyboard safe area

- Mail/Views/SplitView.swift
- Mail/Views/Thread/MessageView.swift
- MailCore/API/MailApiError.swift
- MailCore/API/MailError.swift
- MailCore/Cache/MailboxManager.swift
This is a first step in handling missing messages. Eg. when our thread list is not up to date and we click on a message.
This PR only fixes the case when we try to download the body and the message doesn't exist anymore.
We still need to fix the case for flag update and move but need backend modifications.
> fix: Refresh folder on message not found error

- MailCore/Cache/AccountManager.swift
Old token was kept on logout when logging back in old token was still used.
> fix: Prevent keeping apiFetchers on logout

- MailCore/Cache/MailboxManager.swift
- MailCore/Models/Thread.swift
This could potentially fix the issue where the wrong date is used for some threads.
Not too sure about this "fix" but this seems plausible. 
A default date is set for indexed property. For some reason this date could be used (and written) instead of the one from a message. I cannot test if it fixes the issue because I haven't been able to reproduce it.
We can merge this and test if clients still have the error, if it fixes the issue I will try to investigate in more details.
> fix(Thread): Remove indexed date to prevent default value

- Mail/Utils/NavigationStore.swift
- Mail/Views/Thread List/ThreadListCell.swift
- Mail/Views/Thread List/ThreadListView.swift
- Mail/Views/Thread List/ThreadListViewModel.swift
- Mail/Views/Thread/ThreadView.swift
A split mind issue is causing a selection / view state issue.
Preventing the split mind fixes the problem.
A refactor will be done later to keep a single source of truth, shared with both UI paradyms (compact / large)
> fix: Thread selection issue on iPad

- Mail/MailApp.swift
- Mail/Views/Thread List/ThreadListView.swift
- MailCore/API/Endpoint.swift
- MailCore/Utils/UserActivityController.swift
For now we only support navigating to correct mailbox and folder as we don't share thread ids.
This only works if the connected account on the web is the same as on device.
> feat: Advertise NSUserActivity

- Mail/MailApp.swift
- Mail/NotificationCenterDelegate.swift
- Mail/Utils/NavigationState.swift
- Mail/Views/Bottom sheets/Actions/ActionsViewModel.swift
- Mail/Views/Menu Drawer/Items/MenuDrawerItemsListView.swift
- Mail/Views/Onboarding/OnboardingView.swift
- Mail/Views/Switch User/AccountView.swift
- Mail/Views/Thread List/ThreadListModifiers.swift
- MailCore/API/MailError.swift
- MailCore/Cache/AccountManager.swift
- MailCore/Utils/URLSchemeHandler.swift
Ground work stop using AccountManager.currentAccount.
For now all accesses must be done using: `getCurrentAccount()`
In the future if we want to stop using "one current account" eg. show multiple windows with different mailboxes and accounts we will just have to replace `getCurrentAccount()` with `getPreferredAccount()`.
Depends on #890
> refactor: Decouple current account

- .package.resolved
- Mail/NotificationCenterDelegate.swift
- MailCore/Cache/AccountManager.swift
- Project.swift
This is not a longterm solution but I prefer to have a technically correct solution but blocking rather than the actual code that is crashing the app.
In the near future the AccountManager will be refactored to an Actor to prevent concurrent access.
> fix: Thread safe account manager

- MailCore/Cache/MailboxManager.swift
As body is now a computed property and is compressed we cannot search inside it.
> fix: Do not search over computed body

- .package.resolved
- Project.swift
updated ios-core has a fix on sharing .webloc
> chore: Bump ios-core

- Mail/Views/Bottom sheets/Actions/ActionUtils.swift
- Mail/Views/Thread List/ThreadListMultipleSectionViewModel.swift
- Mail/Views/Thread List/ThreadListSwipeAction.swift
- Mail/Views/Thread/ThreadView.swift
- MailCore/Cache/MailboxManager/MailboxManageable.swift
- MailCore/Cache/MailboxManager/MailboxManager+Message.swift
- MailCore/Cache/MailboxManager/MailboxManager+Thread.swift
- MailCore/Utils/SnackBar/IKSnackBar+Extension.swift
- MailCore/Utils/UndoAction.swift
Only renaming.
UndoRedoAction was misleading as there is no "redoing" only two steps in the undo:
1. Api call to actually cancel the action
2. Api call to refresh the folder where the action was done
> refactor: Rename UndoRedoAction to UndoAction

- Mail/Views/Attachment/ActivityView.swift
- Mail/Views/Attachment/AttachmentPreview.swift
Because of a bad merge, RootViewManageable factory was missing and this would cause a crash. However RootViewManageable is not needed anymore as we should always try to present the view from the current scene.
I removed the RootViewManageable protocol and presented the view using a  UIViewControllerRepresentable
> fix: Present UIActivityViewController using SwiftUI

- Mail/Views/SplitView.swift
- MailCore/Cache/DraftContentManager.swift
- MailCore/Cache/DraftManager.swift
- MailCore/Cache/MailboxManager/MailboxManager+Message.swift
- [Rollback force refresh on new draft stopgap added here](https://github.com/Infomaniak/ios-kMail/pull/817).
- Refresh contact list on app goes into foreground.
- [Previously merged PR](https://github.com/Infomaniak/ios-kMail/pull/931) refresh signatures if needed is required for this to work.
> fix: Refresh signatures on app going to foreground

- Mail/Components/AvatarView.swift
- Mail/Components/RecipientCell.swift
- Mail/Components/ThreadCell.swift
- Mail/Views/Bottom sheets/Actions/ContactActionsView/ContactActionsHeaderView.swift
- Mail/Views/Switch User/AccountCellView.swift
- Mail/Views/Switch User/AccountListView.swift
- Mail/Views/Switch User/AccountView.swift
- Mail/Views/Thread List/ThreadListModifiers.swift
- Mail/Views/Thread/MessageHeaderSummaryView.swift
- Mail/Views/Unavailable Mailbox/UnavailableMailboxesView.swift
`UnavailableMailboxesView` require to use some views without a `mailboxManager`
This PR solves the problem by making the subviews requiring a nullable `mailboxManager` at init.
> Crash missing mailboxManager in UnavailableMailboxesView

- Mail/Components/UnavailableMailboxListView.swift
- Mail/Helpers/AppAssembly.swift
- Mail/Helpers/Notifications/NotificationCenterDelegate.swift
- Mail/Views/Menu Drawer/MailboxManagement/MailboxesManagementView.swift
- Mail/Views/New Message/Header Cells/ComposeMessageSenderMenu.swift
- Mail/Views/Settings/General/ForEachMailboxView.swift
- Mail/Views/Switch User/AccountListView.swift
- MailCore/Cache/AccountManager.swift
- MailCore/Cache/ContactManager/ContactManager+Merge.swift
- MailCore/Cache/ContactManager/ContactManager.swift
- MailCore/Cache/MailboxInfosManager.swift
- MailCore/Cache/MailboxManager/MailboxManager+Message.swift
- MailCore/Cache/MailboxManager/MailboxManager.swift
- MailCore/Cache/NavigationState.swift
- MailCore/Utils/Model/ModelMigrator.swift
- MailCore/Utils/NotificationsHelper.swift
- MailCore/Utils/UserActivityController.swift
- MailNotificationServiceExtension/NotificationService.swift
- MailNotificationServiceExtension/NotificationServiceAssembly.swift
- MailShareExtension/ShareViewController.swift
… in order to keep notifications working without openning the app after an update.
- Force REALM migration to take place early in extension mode (notification + share)
- Fix an issue with share extension not loading the correct realm context in edition of a draft.
- Harden contact update with the use of `ApplicationBackgroundTaskTracker` from core-ui
> fix(realm_migration): soft migration for Mailbox.aliases 

- MailCore/Cache/ContactManager/ContactManager+DB.swift
- MailCore/Cache/ContactManager/ContactManager+Merge.swift
- MailCore/Cache/ContactManager/ContactManager.swift
- MailCore/Models/MergedContact.swift
Some cleanup and minor improvements related to contacts
fix(ContactManager): Remove contacts from DB when does not exist in iphone or infomaniak
feat(ContactManager): reduce getRealm call count.
feat(ContactManager): refresh realm on getRealm() to match the app.
> Clean removed contacts from DB

- MailCore/Cache/MailboxManager/MailboxManager+Message.swift
- MailCore/Cache/MailboxManager/MailboxManager+Thread.swift
- MailCore/Models/Thread.swift
Creation / Update of a Thread (and sorting of related mails) are protected from random termination in background.
> feat: use ApplicationBackgroundTaskTracker to harden thread creation

- MailCore/Utils/Logging.swift
As they are not currently used with by our back-end we do not need to pollute client headers.
> fix: Disable tracing headers introduced with latest Sentry versions

- .package.resolved
- MailCore/Models/Message.swift
- MailCore/Utils/SentryDebug.swift
Bug is now fixed, rollback the Sentry error.
Reverts Infomaniak/ios-kMail#961
> Revert "feat: send an error to sentry on date parsing issue"

- Mail/Views/Thread/MessageHeaderDetailView.swift
Bug fix: Sometimes clicking on a contact in CC won't open the contact bottom sheet
It happens with most of the github mails
> fix(ContactSheet): Show on CC

- Mail/Components/AvatarView.swift
- Mail/Components/ThreadCell.swift
- Mail/Components/ThreadCellDetailsView.swift
- Mail/Components/ThreadCellHeaderView.swift
- Mail/Components/ThreadCellInfoView.swift
- Mail/Views/Menu Drawer/Folders/FolderCell.swift
- Mail/Views/Thread List/ThreadListCell.swift
- MailCore/Cache/ContactManager/ContactManager+DB.swift
- MailCore/Cache/ContactManager/ContactManager.swift
- MailCore/Models/CommonContact.swift
| Module / View Type     | Count | Total Duration | Min Duration | Avg Duration | Max Duration | Std Dev Duration |
|------------------------|-------|----------------|--------------|--------------|--------------|------------------|
| Before                 |       |                |              |              |              |                  |
| ThreadListCell         | 111   | 40.87 ms       | 266.88 µs    | 368.20 µs    | 3.38 ms      | 296.85 µs        |
| ThreadListSwipeActions | 111   | 19.87 ms       | 152.62 µs    | 179.00 µs    | 510.17 µs    | 42.77 µs         |
| ThreadCell             | 19    | 18.18 ms       | 293.71 µs    | 956.76 µs    | 2.15 ms      | 778.09 µs        |
| After                  |       |                |              |              |              | …
> perf: ThreadListCell redraw improvements

- Mail/Views/Bottom sheets/Actions/ContactActionsView/ContactActionView.swift
> If you want to show multiple sheets in SwiftUI, it’s only possible by triggering the second sheet from inside the first – you shouldn’t attach both sheet() modifiers to the same parent view.
[https://www.hackingwithswift.com/quick-start/swiftui/how-to-present-multiple-sheets](https://www.hackingwithswift.com/quick-start/swiftui/how-to-present-multiple-sheets)
> fix: Dismiss modal before showing another one

- Mail/Views/Menu Drawer/FolderListView.swift
- Mail/Views/Menu Drawer/Folders/FolderCell.swift
- Mail/Views/SplitView.swift
This avoids workarounds with .isInvalidated. 
Fetching folders when coming back from background was also broken. This is now fixed.
> fix: Freeze folders before passing to views

- Mail/Views/Thread/MessageListView.swift
- Mail/Views/Thread/ThreadView.swift
An attempt at fixing the "scroll to top in a loop" bug ~~that seems to be a macOS only issue~~.
EDIT: 
The issue comes from `.onAppear` not properly called _on iPad_ (so macOS as well as of today).
A quickfix is to give a proper`id` to the `MessageListView`, and it works fine. I mean no random scroll, and an expected scroll to last message of a thread, like today on iPhone.
> fix: Scroll loop issue on iPadOS and macOS

- MailCore/Cache/AccountManager/AccountManager.swift
Errors are catched later either by preloading screen or when switching root view state
> fix: Ignore error when fetching folders on account creation

- MailCore/Models/Thread.swift
The threads returned by search route can sometimes return a nil date.
> fix: Provide default date when decoding Thread

- Mail/Components/AvatarView.swift
- Mail/Components/InitialsView.swift
- MailCore/Cache/ContactManager/ContactManager+DB.swift
- MailCore/Cache/ContactManager/ContactManager+Merge.swift
- MailCore/Cache/ContactManager/ContactManager.swift
- MailCore/Models/MergedContact.swift
With the current ContactManager logic, we can only have one MergedContact per email address.
However, several contacts can have the same email address but a different name.
It even happens that some API contacts share the same name and email address. In this case, we only keep one MergedContact, but merge the interesting data together (such as the avatar).
> fix(ContactManager): Do not index contacts by email

- Mail/Components/AvatarView.swift
Useful when we have no recipient for example
> feat(AvatarView): Add EmptyContact case

- MailCore/Utils/Logging.swift
We are doing this for multiple reasons:
- We never used this feature so this avoids useless disk writes
- We want to slowly move away from CocoaLumberjack dependency
- There is a possibility that writing to this file both from the main app and the notification extension can cause `0xdead10cc` error codes
> fix: Remove log to file

- Mail/AppDelegate.swift
- Mail/Helpers/MailTargetAssembly.swift
- Mail/MailApp.swift
- MailAppIntentsExtension/MailAppIntentsExtension.swift
- MailAppIntentsExtension/MailAppIntentsTargetAssembly.swift
- MailCore/Utils/TargetAssembly.swift
- MailNotificationServiceExtension/NotificationService.swift
- MailShareExtension/MailShareExtensionTargetAssembly.swift
- MailShareExtension/ShareViewController.swift
Instead of EarlyDI hook each target has now a class extending `TargetAssembly`.
`getCommonServices` is the minimal list of all the services shared by the targets.
Each target should subclass `TargetAssembly` and override `getTargetServices` to provide additional, target related, services.
I also noticed that AppDelegate incorrectly recalled EarlyDIHook so I removed it.
> refactor: Improved factory splitting for each target

- Mail/Views/New Message/Attachments/Attachable.swift
- MailCore/Cache/AttachmentsManagerWorker/AttachmentsManagerWorker.swift
*** conditions may apply, depends on type of underlying NSItemProvider.
> feat: Attachment title will be used to populate Draft Subject

- .github/CODEOWNERS
This pull request removes the CODEOWNERS file, allowing us to select our own reviewers or fallback to the iOS team if no specific reviewer is necessary. This change is expected to improve our GitHub notifications.
> feat: Remove CODEOWNERS file

- Mail/ComposeMessageScene.swift
- Mail/DisplayThreadScene.swift
- Mail/MailApp.swift
- Mail/RootView.swift
- Mail/UserAccountScene.swift
- Mail/UserAccountWindow.swift
- MailCore/Cache/MainViewState.swift
- MailCore/Cache/RootViewState.swift
RootViewState now owns the MainViewState.
UserAccountScene now has it's own RootViewState. Each window could theoretically handle it's own account.  
Other WindowGroups that do not depend on an account are declared along side the UserAccountScene.
> refactor: Improved RootViewState management

- Mail/Views/Thread List/ThreadListModifiers.swift
The betas of iOS 17.4 had an issue which caused the title of the navbar to be wrongly displayed. It was fixed in the final version.
> chore: Remove iOS 17.4 patch for toolbar

- MailCore/Cache/MailboxManager/MailboxManager+Thread.swift
> fix: Prevent accessing invalidated Thread

- MailCore/Utils/Logging.swift
Since we use SwiftUI. This is useless and it generates noise in breadcrumbs
> fix: Disable some UIKit tracing

- Mail/UserAccountScene.swift
- MailCore/Utils/Constants.swift
To test that a single window is restored simply force quit the app or stop the app from Xcode
> fix: Ensure UserAccountScene WindowGroup has an identifier

- .package.resolved
- Mail/Views/New Message/Attachments/AttachmentsManager.swift
- Mail/Views/New Message/ComposeMessageIntentView.swift
- Mail/Views/New Message/ComposeMessageView.swift
- MailCore/Cache/Attachments/AttachmentsManagerWorker/AttachmentsManagerWorker.swift
- MailCore/Cache/Attachments/TextAttachable.swift
- MailShareExtension/Attachment/SafariKeyValueToHTMLAttachment.swift
- MailShareExtension/Attachment/TxtToHTMLAttachment.swift
- MailShareExtension/Attachment/WeblocToHTMLAttachment.swift
- MailShareExtension/ComposeMessageWrapperView.swift
- Project.swift
Bump swift-concurrency : https://github.com/Infomaniak/swift-concurrency/pull/4
> feat: Text shared via the ShareExtension is sanitized and added to a new draft

- Mail/Views/Bottom sheets/ReportDisplayProblemView.swift
- Mail/Views/Thread/WebView/WebViewModel+MessageHandler.swift
- MailCore/API/MailError.swift
- MailCore/Utils/Error+Extension.swift
- MailCore/Utils/SentryDebug.swift
Easier to read commit by commit.
I extracted logic to choose whether we should send the events or not  -> `shouldSendToSentry`
Errors are now sent only if:
- They are not cancel errors (Native or wrapped in Alamofire)
- They are not network errors
MailErrors are now encodable to improve their readability in Sentry
Some deprecated Sentry calls where replaced
Warnings regarding casting of some errors in Sentry's `context` are now handled correctly
> fix: Improve sentry error logging

- Mail/Components/ThreadCell/ThreadCell.swift
ThreadCellDataHolder used a non lazy filter function to init which could cause hangs. Switching to a lazy filtering with predicate should help reducing the cost of the init.
> perf(ThreadCell): Use realm lazy query instead of iterating through all messages

- .github/workflows/ci.yml
- .github/workflows/periphery.yml
- .github/workflows/uitests.yml
- .mise.toml
- .periphery.yml
- scripts/periphery.sh
Unused code is now detected using periphery. (https://github.com/peripheryapp/periphery)
For every PR a comment is generated which gives a list of unused code + the count.
> ci: Detect unused code with Periphery

- Mail/Views/MoveEmailView.swift
- Mail/Views/Thread List/FlushFolderView.swift
- MailCore/Cache/MailboxManager/MailboxManager+Thread.swift
Fix for Sentry: MAIL-IOS-RW5
In some calls the folder wasn't frozen. This is tricky to debug because async await doesn't always switch thread so the crash doesn't always occur.
> fix: Incorrect thread refresh folder

- Mail/Views/New Message/Attachments/AttachmentsHeaderView.swift
- MailResources/Localizable/de.lproj/Localizable.strings
- MailResources/Localizable/en.lproj/Localizable.strings
- MailResources/Localizable/es.lproj/Localizable.strings
- MailResources/Localizable/fr.lproj/Localizable.strings
- MailResources/Localizable/it.lproj/Localizable.strings
- MailShareExtension/ComposeMessageWrapperView.swift
General improvements for the PleaseLoginView:
- Fix missing padding
- Stop using spacer
- Fix french translation
Fix crash with attachements:
- Fix for MAIL-IOS-X7Y, attachment delete button could be tapped a second time while being removed ending with an invalidated object crash.
> fix(ShareExtension): UI fixes + prevent invalidated attachment crash

- Package.resolved
- Package.swift
Realm had some changes in the way it is built after upgrading from 10.49.2 to 10.49.3 (and 10.50.0) to comply with the new privacy manifest requirements. 
Those changes broke Tuist's default way of building and linking dependencies. I had to do some modifications to the Package.swift to force Tuist to link the library as static as it was previously doing it by itself.
> chore: Upgrade dependencies + Special fix to allow Realm compilation

- Mail/Views/Search/SearchContactsSectionView.swift
- Mail/Views/Search/SearchHistorySectionView.swift
- Mail/Views/Search/SearchThreadsSectionView.swift
- Mail/Views/Search/SearchView.swift
On iOS 16.0, SwiftUI seems confused by the if blocks directly in the `List`. For some reason, moving the condition to the subviews fixes the issue.
To reproduce the issue, use a device/simulator on iOS 16.0 (.0 is important) with a clean DB to start from scratch.
> fix: Conditionally display views in subviews

- MailCore/Cache/MailboxManager/MailboxManager+Folders.swift
We cannot freeze object during a write transaction. Realm will raise exception -> Cannot freeze an object in the same write transaction as it was created in.
Previously this was working because write transaction was done inside backgroundRealm.execute block.
Fix for: MAIL-IOS-1285
> fix: Do not freeze folder inside write transaction

- MailNotificationContentExtension/NotificationViewController.swift
- MailNotificationServiceExtension/NotificationService.swift
Sometimes NotificationService crashes on launch due to a migration issue. 
However, Sentry userid is not set yet and we end up with a generic user id.
This PR simply moves Sentry userid before migration.
> fix: Ensure Sentry user is set earlier to detect migration issues

- Mail/StandardWindowViewModifier.swift
- Mail/Views/Thread/Message/MessageSubHeaderView.swift
- Mail/Views/Thread/Message/MessageView.swift
- MailCoreUI/Extensions/UIWindow+Extension.swift
- MailNotificationContentExtension/NotificationViewController.swift
Hide some header components in the message when displayed in the notification preview.
Moved header components to `MessageSubHeaderView`.
Better read commit per commit.
| Before | After |
| --- | --- |
| ![CleanShot 2024-05-29 at 14 59 40@2x](https://github.com/Infomaniak/ios-kMail/assets/5843044/f8783d80-68aa-43b5-87e0-911b96aacb42) | ![CleanShot 2024-05-29 at 14 59 26@2x](https://github.com/Infomaniak/ios-kMail/assets/5843044/65bbe974-9656-4c49-b3be-dd1b1c879fe2) |
> fix: Remove attachments and calendar events from notification preview

- MailCore/Cache/AccountManager/AccountManager.swift
- Package.resolved
- Package.swift
Noticed some threading issues on Sentry that could be related to currentAccount not being thread safe. Since we now have a `SendableProperty` I made a quickwin using it. It was one of the last property not thread safe in `AccountManager`
> fix(AccountManager): Use SendableProperty for currentAccount

- Mail/Views/Menu Drawer/FolderListViewModel.swift
- MailCore/Models/Folder.swift
- MailCore/Models/NestableFolder.swift
Display favorites folders at the top of the userFolders list (see before/after screenshots).
For nested folders, favorites go to the top of the children's list.
> feat: Sort favorites folders

- Mail/Views/Alerts/LogoutConfirmationView.swift
- Mail/Views/Bottom sheets/Actions/ActionsView.swift
- MailCore/Models/Contact/CommonContact.swift
For some legacy reasons `account.user` is forced unwrap this can lead to crashes. 
This PR aims to reduce the number (not yet to 0) of places where user is not safely accessed.
In an ideal world without data races, when the user is nil the account shouldn't be connected but this not (yet) the case.
> fix: Treat user as nullable

- Mail/Views/Menu Drawer/MenuHeaderView.swift
- Mail/Views/New Message/Select Mailbox/CurrentComposeMailboxView.swift
- Mail/Views/New Message/Select Mailbox/SelectComposeMailboxView.swift
- Mail/Views/New Message/Select Mailbox/SelectedMailboxView.swift
- Mail/Views/Thread/Message/MessageHeader/MessageHeaderDetailView.swift
- Mail/Views/Thread/Message/MessageHeader/MessageHeaderSummaryView.swift
- MailCore/UI/UIConstants.swift
Read commit by commit:
`fix: Manually pass environmentObject to ContactActionsView` -> ensure we correctly pass the env on macOS
`fix(SelectedMailboxView): Do not depend on EnvironmentObject for mailboxmanager` -> ensure we have a mailboxManager (and the correct one) for each cell
`fix: Add MenuHeaderView to toolbar only on macOS` -> add the MenuHeaderView elements directly to the menu bar
> fix: Small fixes for macOS

- Mail/Views/Thread/Message/Attachment/AttachmentsView.swift
This PR fix the padding that was wrong when scrolling the attachments view. The scroll didn't go all the way to the edge of the screen.
> fix: Padding when scrolling attachments

- Mail/Views/Search/SearchViewModel+Search.swift
If a search is currently running, we cancel it before starting a new one.
However,  - depending on how fast you type and other async side effects - the search task could be canceled but `isLoading` was still true. Right after the search is canceled we call fetchThreads with the new search text but because `isLoading` is still true we abort.
For example:
If you type T-E-S-T with the right timing, only TES would be sent to the search. It would lead to search results that seem correct but in fact a letter is missing.
This PR sets `isLoading` to false right after canceling the search request.
> fix: Incorrect search results displayed

- Mail/Views/Thread/Message/MessageView.swift
- MailCore/API/MailError.swift
Until now we were fetching content and calendar events for every message even if it wasn't expanded. 
The view would also cancel the fetching task when disappearing and display an error.
Now both message content and calendar event are fetched in parallel and only if the message is expanded.
If the expanded state changes we try to fetch everything.
> fix: Only fetch message body if expanded + fetch calendar event in parallel

- Mail/Utils/FloatingActionButtonModifier.swift
- Mail/Views/Menu Drawer/Folders/FolderCell.swift
- Mail/Views/Search/SearchView.swift
- Mail/Views/Thread List/ThreadListCell.swift
- Mail/Views/Thread List/ThreadListModifiers.swift
- Mail/Views/Thread/Message/MessageView.swift
- MailResources/Localizable/de.lproj/Localizable.strings
- MailResources/Localizable/en.lproj/Localizable.strings
- MailResources/Localizable/es.lproj/Localizable.strings
- MailResources/Localizable/fr.lproj/Localizable.strings
- MailResources/Localizable/it.lproj/Localizable.strings
Improve application accessibility and focus for Full Keyboard Access users. 
<b>Full Keyboard Access : </b>
- enable message expansion
- enable folder switching
- enable multiple thread selection
- display and enable bottom bar actions on multiple selection
See some visual examples of the changes in the screenshots below.
Screenshots show specific actions using only the keyboard.
Tested on iPhone and iPad.
<h4 align="center">Message expansion</h4>
<p align="center" style="display:flex; justify-content: space-between;">
</p>
<h4 align="center">Search by keyword</h4>
<p align="center" style="display:flex; justify-content: center;">
</p>
<h4 align="center">Multiple selection and bottom bar actions</h4>
<p align="center" style="display:flex; justify-content: center;">
</p>
> chore: Improve accessibility II with full keyboard access

- Mail/Components/Custom Buttons/AccountButton.swift
- Mail/Components/Custom Buttons/ModalButtonsView.swift
- Mail/Components/Custom Buttons/SearchButton.swift
- Mail/Components/MailboxListView.swift
- Mail/Helpers/RichTextEditor.swift
- Mail/Views/Alerts/CreateFolderView.swift
- Mail/Views/Menu Drawer/Folders/FolderCell.swift
- Mail/Views/Menu Drawer/Items/MenuDrawerItemsListView.swift
- Mail/Views/New Message/ComposeMessageHeaderView.swift
- Mail/Views/New Message/Header Cells/ComposeMessageCellRecipients.swift
- Mail/Views/Search/SearchView.swift
- Mail/Views/Switch User/AccountListView.swift
- Mail/Views/Thread List/ThreadListCell.swift
- Mail/Views/Thread List/ThreadListModifiers.swift
- Mail/Views/Thread/Message/MessageHeader/MessageHeaderSummaryView.swift
- Mail/Views/Thread/Message/MessageView.swift
- MailCoreUI/Components/ChevronIcon.swift
- MailCoreUI/Components/CloseButton.swift
- MailCoreUI/Components/SearchTextField.swift
- MailResources/Localizable/de.lproj/Localizable.strings
- MailResources/Localizable/en.lproj/Localizable.strings
- MailResources/Localizable/es.lproj/Localizable.strings
- MailResources/Localizable/fr.lproj/Localizable.strings
- MailResources/Localizable/it.lproj/Localizable.strings
Improve application accessibility and focus for VoiceOver users. 
<b>VoiceOver : </b>
- add missing labels and paddings
- add escape gesture (Z gesture)
- enlarge tap area for expanding a message (sender + date)
- Bonus : add keyboard shortcuts for all users even without VoiceOver enabled (Escape to cancel / go back; Enter to confirm)
See some visual examples of the changes in the screenshots below.
Most changes use sound or gesture.
Tested on iPhone and iPad.
<h3 align="center">Before / After</h3>
<p align="center" style="display:flex; justify-content: space-between;">
</p>
> feat: Improve accessibility

- MailCore/Cache/Actions/ActionsManager.swift
Problem :
We're adding the duplicates at the beginning of the `performAction` function
Then we're calling `lastMessagesAndDuplicatesToExecuteAction` which will look if it's a single message or not
It will find that it is not a single message since we've added the duplicates and it will be treated as one or many thread. But it should be a single message !
> fix: Use lastMessagesAndDuplicatesToExecuteAction on original messages

- Mail/Views/Bottom sheets/Actions/ActionsPanelViewModifier.swift
- MailCore/API/Endpoint.swift
- MailCore/API/MailApiFetcher/MailApiFetcher+Common.swift
- MailCore/Cache/Actions/Action+List.swift
- MailCore/Cache/Actions/ActionOrigin.swift
- MailCore/Cache/Actions/ActionsManager.swift
- MailCore/Models/ShareMailLinkResult.swift
- MailResources/Assets.xcassets/email-action-share.imageset/Contents.json
- MailResources/Assets.xcassets/email-action-share.imageset/email-action-share.svg
- MailResources/Localizable/de.lproj/Localizable.strings
- MailResources/Localizable/en.lproj/Localizable.strings
- MailResources/Localizable/es.lproj/Localizable.strings
- MailResources/Localizable/fr.lproj/Localizable.strings
- MailResources/Localizable/it.lproj/Localizable.strings
- Link expires after 30 days
- If user create a new link for the same message, old one is automatically disabled
- For later in V2: "Revoke link" as shown on Figma
> feat: Share mail link

- MailCore/Cache/AccountManager/AccountManager.swift
- MailCore/Utils/URLSchemeHandler.swift
In preparation for it's removal in InfomaniakCore. 
Token should always be fetched from the single source of truth which is `TokenStore`
> fix: Stop using account.token

- MailCore/UI/UIConstants.swift
Updated scrollObserverThreshold so that the new message button's size doesn't get updated when cells are added
> fix: Updated scrollObserverTreshold

- Mail/Views/Thread/Message/InlineAttachmentWorker.swift
Disable image compression within webview if LockdownMode is ON as image will not be displayed properly.
> fix(BodyImageProcessor): Disable image compression if LockdownMode is ON

- MailCore/Models/Contact/CommonContactCache.swift
- MailCore/Models/Contact/ContactConfiguration.swift
- c618c21248c5fbbcaece21ae7058f71b1c666c55 Wrap CommonContact init in an ExpiringActivity. For some reason the init can take too long and the OS would kill the app.
-  4fee38d19c864b48f3fa83bd425077cb53c86cb6 Correctly freeze the given correspondant (and bimi), I hope this can resolve some bad access too.
> fix: Prevent crashes while resolving contacts

- Mail/Views/Attachment/AttachmentPreview.swift
- MailResources/Mail.entitlements
This PR fix the bug where user couldn't save an attachement on MacOS.
It has been decided to have one "share button" on iOS and one "share button" and one "download button" on MacOS.
> fix: Download attachments for Mac

- MailCore/Cache/MailboxManager/MailboxManager+Thread.swift
- MailCore/Models/Folder.swift
When moving more than a page of messages in a folder, If the folder was empty before, we won't be able to fetch all messages.
> fix: Reset folder if empty

- Tuist/Package.swift
As seen with tests on previous Xcode versions, Xcode 16 seems to also link differently Previews. With our current tuist configuration this leads to duplicate classes which causes problems with the DI singleton.
> fix: Expose InfomaniakDI as Framework

- MailCore/Cache/Actions/Action+List.swift
As suggested by Valentin, I changed a var in let, and remove the "selectAll" matomo nam in the Action list.
https://github.com/Infomaniak/ios-kMail/pull/1544#discussion_r1772697608
> style: Change var in let, remove "selectAll" Matomo name

- Mail/Views/New Message/AutocompletionView.swift
Apple Mail doesn't animate the autocompletion results and it feels more natural.
> chore(AutocompletionView): Remove animation

- Mail/Proxy/Implementation/CacheManager.swift
- Mail/Proxy/Protocols/CacheManageable.swift
- Mail/UserAccountScene.swift
- Mail/Views/SplitView.swift
- MailCore/Cache/RootViewState.swift
- MailNotificationContentExtension/Proxy/CacheManager.swift
- MailShareExtension/Proxy/CacheManager.swift
CacheManager wasn't doing anything because MainViewState.account wasn't set correctly.
`MainViewState.account` was a double source of truth so I removed it.
CacheManager is now called from SplitView.
> fix: CacheManager not called

- Mail/Views/Thread/MessagesWorker.swift
To fetch a calendar event, we need an Attachment. If we are fetching the message for the first time, the message doesn't have any Attachment, so fetching a calendar event in parallel will fail.
> fix(CalendarEvent): Do not load in parallel message and calendar

- Mail/Components/ActionsPanelButton.swift
- Mail/Views/Bottom sheets/Actions/ActionsPanelViewModifier.swift
- Mail/Views/Search/SearchModifiers.swift
- Mail/Views/Thread List/ThreadListModifiers.swift
- Mail/Views/Thread List/ThreadListSwipeAction.swift
- Mail/Views/Thread/WebView/ThreadViewToolbarModifier.swift
- MailCoreUI/Utils/AdaptivePanelViewModifier.swift
This is necessary to fix an issue introduced by Apple on iOS 18.1 and fixed on iOS 18.2 (135231043)
> fix(iOS 18.1): Set explicit arrow edge position for popovers

- Mail/Components/ThreadCell/ThreadCellAvatarCheckboxView.swift
- Mail/Views/Thread List/MultipleSectionViewModel.swift
- Mail/Views/Thread List/ThreadListCell.swift
- Mail/Views/Thread List/ThreadListView.swift
- Removed `tapGesture` in favor of `Button` to better align with what SwiftUI expects.
- Workaround the navigation issue by disabling the multiple selection in the next run loop. (Basically added a DispatchQueue.main.async 🙃)  
Tested in simulator on iOS:
- 18.1
- 17.5
- 16.4
- 15.5
I'm open to better ideas instead of the workaround.
> fix: Multiple selection shouldn't navigate

- Tuist/Package.resolved
- Tuist/Package.swift
Library bump, given the unit tests on the library I'm confident it will work smoothly.
> chore: Bump swift-concurrency to 1.0.0

- Mail/AppDelegate.swift
In the initial version of the macOS we didn't restore correctly windows. 
Now that we handle mutli-windows we can enable state restoration back.
> fix: Reenable state restoration on macOS

- MailCore/Utils/Logging.swift
Apple warns us about "slow code path on launch" one of them is checking if we are in TestFlight while launching.
This resolution is now lazy and only executed when sending events
> fix: Lazy env for Sentry

- Mail/Views/AI Writer/AIModel.swift
- Mail/Views/New Message/ComposeMessageHeaderView.swift
- Mail/Views/New Message/ComposeMessageIntentView.swift
- Mail/Views/New Message/ComposeMessageView.swift
- Mail/Views/New Message/Header Cells/ComposeMessageSenderMenu.swift
- Mail/Views/New Message/Header Cells/SenderMenuCell.swift
- MailCore/Cache/DraftContentManager.swift
- MailCoreUI/Helpers/PreviewHelper.swift
> fix: Prevent a crash on invalidated Draft

- MailCore/Cache/Actions/Action+List.swift
This fixes the "share mail" button when you are in multi-selection mode but only have one email selected.
> fix: Single mail in multi-selection view sharing

- Mail/Views/Thread/Message/Attachment/AttachmentsView.swift
- Mail/Views/Thread/Message/MessageSubHeaderView.swift
- MailCore/Cache/MailboxManager/MailboxManager+Message.swift
- MailCore/Cache/MailboxManager/MailboxManager.swift
- MailCore/Models/Attachment.swift
- MailCore/Models/Message.swift
Display non inline attachments files even with contentId
> fix: Show not inline files

- MailCore/Models/AddressBook.swift
- MailCore/Models/Attachment.swift
- MailCore/Models/Draft.swift
- MailCore/Models/MergedContact.swift
- MailCore/Models/Message.swift
- MailCore/Models/SearchHistory.swift
- MailCore/Models/Signature.swift
- MailCore/Models/SwissTransferAttachment.swift
Objects with existing custom implementation are left as is (ie: Thread, Folder, ...)
> fix: Use ObjectKeyIdentifiable for Realm objects

- MailCore/Cache/MailboxManager/MailboxManager+Thread.swift
- MailCore/Models/Thread.swift
- MailCore/Utils/SentryDebug.swift
A `was_snoozed` message is an `unsnoozed` message read by the user.
As storing this state is irrilevant, we simply reset all the snoozed properties to nil.
> feat(Snooze): Handle `was_snoozed` state

- MailCore/Cache/Actions/ActionsManager.swift
Quick fix to compare folders by remoteId instead of comparing the objects themselves.
> fix: Compare folder by remote id

- Tuist/Package.resolved
- Tuist/Package.swift
Having a discrete PR for this is a good reference point to track if any issue and/or performance improvements from the Lock based DI.
> chore: Bump DI to the version using an internal lock

- Mail/Views/Thread List/DragAndDropModifier.swift
Some kind of retain cycle was created because of the closure. Observing this way is also more correct.
> fix: Correctly observe drop success

- Mail/Views/Search/SearchThreadsSectionView.swift
- Mail/Views/Thread List/ThreadListCell.swift
- Mail/Views/Thread List/ThreadListModifiers.swift
- Mail/Views/Thread List/ThreadListSwipeAction.swift
- Mail/Views/Thread List/ThreadListView.swift
- MailCore/Cache/MainViewState.swift
- MailCore/Utils/FlushAlertState.swift
- MailCoreUI/Components/AvatarView.swift
AvatarViewModel was recreated because the parent view was updated too often + a drop on of the contact cache when moving in the background. 
The update was caused by the view not remembering `@ModalState`. ModalState is now moved in the MainViewState.
> fix: Contact flickering

- Mail/Views/Alerts/ConfirmationBlockRecipientView.swift
- Mail/Views/Alerts/ReportPhishingView.swift
- Mail/Views/Bottom sheets/Actions/ActionsPanelViewModifier.swift
- Mail/Views/Bottom sheets/Actions/ActionsView.swift
- Mail/Views/Bottom sheets/Actions/BlockSenderView.swift
- Mail/Views/Bottom sheets/Actions/ReportJunkView.swift
- MailCore/API/Endpoint/Endpoint.swift
- MailCore/API/MailApiFetcher/MailApiFetchable.swift
- MailCore/API/MailApiFetcher/MailApiFetcher+Common.swift
- MailCore/API/MailApiFetcher/MailApiFetcher+Extended.swift
- MailCore/Cache/Actions/Action+List.swift
- MailCore/Cache/Actions/ActionOrigin.swift
- MailCore/Cache/Actions/ActionsManager.swift
- MailCore/Cache/MailboxManager/MailboxManager+Message.swift
- MailCore/Cache/MailboxManager/MailboxManager+Thread.swift
- MailCore/Utils/BlockRecipientState.swift
- MailResources/Localizable/de.lproj/Localizable.strings
- MailResources/Localizable/de.lproj/Localizable.stringsdict
- MailResources/Localizable/en.lproj/Localizable.strings
- MailResources/Localizable/en.lproj/Localizable.stringsdict
- MailResources/Localizable/es.lproj/Localizable.strings
- MailResources/Localizable/es.lproj/Localizable.stringsdict
- MailResources/Localizable/fr.lproj/Localizable.strings
- MailResources/Localizable/fr.lproj/Localizable.stringsdict
- MailResources/Localizable/it.lproj/Localizable.strings
- MailResources/Localizable/it.lproj/Localizable.stringsdict
This PR allows to:
- Report multiple messages suspected of phishing
- Report multiple messages as spam
- Block multiple users
_The report for junk floating panel_
> fix: Multiselect report for junk

- Mail/Views/Schedule/ScheduleFloatingPanel.swift
This PR resolves a crash occurring on macOS when trying to schedule a sending.
The issue was due to platform-specific behavior not being properly handled.
This fix ensures stability across platforms.
> fix: Crash on showing schedule floating panel macOS

- Mail/Views/Menu Drawer/Folders/FolderCell.swift
- Mail/Views/MoveEmailView.swift
- Mail/Views/Thread List/DragAndDropModifier.swift
- Mail/Views/Thread List/ThreadListView.swift
- MailCore/Cache/MailboxManager/MailboxManager+Folders.swift
- MailCore/Cache/MailboxManager/MailboxManager.swift
- MailCore/Models/Folder.swift
- MailCore/Models/Message.swift
- MailCore/Models/Thread.swift
Disable drag & drop for non-movable mails and restricted folders. Prevents users from dragging emails that shouldn't be moved and blocks dropping into disallowed folders to improve UX consistency and prevent unintended actions.
> fix: Disable unwanted drag&drop

- Mail/Views/Settings/SettingsView.swift
- Tuist/Package.resolved
Small correction to display the "+" of "my kSuite+" when it's needed
> fix: Correct my ksuite label

- Mail/Views/Encryption/EncryptionButton.swift
- Mail/Views/Encryption/EncryptionStateView.swift
- Mail/Views/New Message/ComposeEditor/EditorToolbarAction.swift
- Mail/Views/New Message/ComposeEditor/Mobile/AddAttachmentMenu.swift
- Mail/Views/New Message/ComposeEditor/Mobile/EditorMobileToolbarView.swift
- Mail/Views/New Message/ComposeEditor/Mobile/MobileMainToolbarView.swift
- Mail/Views/New Message/ComposeEditor/Mobile/MobileToolbarButton.swift
- Mail/Views/New Message/ComposeMessageView.swift
I don't have a strong opinion about this but on macOS I think the encrypt button should stay in the navbar.
If you disagree you can move it back to the toolbar.
For now on mobile the encrypt button is trailing on the left after the other actions. 
Maybe we want to have it alone on the right.
> fix(Encryption): Move toolbar button
