Infomaniak/ios-kMail

- .swiftlint.yml
- Mail/Utils/KeychainHelper.swift
- Project.swift
- scripts/lint.sh
Signed-off-by: Ambroise Decouttere <ambroise.decouttere@infomaniak.com>
> SwiftLint added

- Mail/Info.plist
- Project.swift
> Fix app crashe + Add automatic code signing

- Mail/AppDelegate.swift
- Mail/Base.lproj/Main.storyboard
- Mail/SceneDelegate.swift
- Mail/Utils/MatomoUtils.swift
- Mail/Views/LoginViewController.swift
> Account persistence

- Mail/Info.plist
- Mail/SceneDelegate.swift
- Mail/Views/New Message/NewMessageView.swift
> Handle mailto

- Mail/Views/New Message/NewMessageView.swift
> Switch mailbox in new message view

- Mail/Views/SplitView.swift
- Mail/Views/Thread List/ThreadListView.swift
- Mail/Views/Thread List/ThreadListViewModel.swift
- MailCore/API/Endpoint.swift
- MailCore/API/MailApiFetcher.swift
- MailCore/Cache/MailboxManager.swift
- MailCore/Models/Draft.swift
- MailCore/Models/Message.swift
- MailCore/Models/Thread.swift
> Thread swipe actions

- Mail/Views/LoginView.swift
> Fix login on iPad

- Mail/Views/Thread List/EmptyListView.swift
- Mail/Views/Thread List/ThreadListView.swift
> Add empty thread list view

- Mail/Views/Thread List/ThreadListView.swift
- Mail/Views/Thread List/ThreadListViewModel.swift
- MailCore/API/Endpoint.swift
- MailCore/API/MailApiFetcher.swift
- MailCore/Cache/MailboxManager.swift
- MailCore/Models/Thread.swift
> Infinite scroll in thread list

- Mail/Views/Thread List/ThreadListCell.swift
> Thread list preview

- Mail/Views/Thread List/ThreadListViewModel.swift
- Mail/Views/Thread/ThreadView.swift
> Fix crash in thread view

- Mail/Helpers/RichTextEditor.swift
- Mail/SceneDelegate.swift
- Mail/Views/New Message/NewMessageView.swift
- Mail/Views/New Message/RecipientCellView.swift
- Mail/Views/Thread List/ThreadListView.swift
- Mail/Views/Thread/ThreadView.swift
- MailCore/API/MailApiFetcher.swift
- MailCore/Cache/MailboxManager.swift
- MailCore/Models/Draft.swift
- MailCore/Models/Signature.swift
> Fix values bug in New Message View

- Mail/Views/Thread List/EmptyListView.swift
- Mail/Views/Thread List/ThreadListView.swift
> Fix refresh in thread list

- Mail/Views/Actions/ActionsView.swift
- Mail/Views/Actions/ActionsViewModel.swift
- Mail/Views/Thread List/ThreadListView.swift
- Mail/Views/Thread/ThreadView.swift
- MailCore/Cache/MailboxManager.swift
> Actions menu reply (reply & archive)

- .package.resolved
- Mail/AppDelegate.swift
- Mail/Views/LoginView.swift
- MailCore/API/MailApiFetcher.swift
- MailCore/Cache/AccountManager.swift
> Fix date profile

- Mail/Views/Settings/SettingsOptionView.swift
- Mail/Views/Settings/SettingsViewModel.swift
- Mail/Views/SplitView.swift
- Mail/Views/Thread List/ThreadListView.swift
- Mail/Views/Thread List/ThreadListViewModel.swift
- MailCore/API/Endpoint.swift
- MailCore/API/MailApiFetcher.swift
- MailCore/Cache/MailboxManager.swift
- MailCore/Models/Message.swift
- MailCore/Models/Thread.swift
- MailCore/Utils/MailUserDefaults+Extension.swift
> Swipe actions settings

- Mail/Utils/Formatters.swift
- Mail/Views/Thread List/ThreadListCell.swift
- Mail/Views/Thread/MessageHeaderView.swift
- MailCore/Models/Thread.swift
- MailCore/Utils/Constants.swift
> Improve thread date formatting

- Mail/Views/Thread/MessageView.swift
- Mail/Views/Thread/ThreadView.swift
> Read all messages from thread on ThreadListView

- MailCore/Cache/MailboxManager.swift
> Fix save thread

- Mail/AppDelegate.swift
- Mail/Views/Menu Drawer/MailboxManagement/MailboxCell.swift
- Mail/Views/Menu Drawer/MailboxManagement/MailboxesManagementButtonView.swift
- Mail/Views/Menu Drawer/MailboxManagement/MailboxesManagementView.swift
- Mail/Views/Switch User/AccountCellView.swift
- Mail/Views/Switch User/AccountListMailView.swift
- Mail/Views/Switch User/AccountListView.swift
- MailCore/API/Endpoint.swift
- MailCore/Models/Mailbox.swift
> Show mailbox unread count

- Mail/Views/Menu Drawer/Folders/FolderCell.swift
- MailCore/Utils/Constants.swift
> MenuDrawer: folder hierarchy

- Mail/Views/New Message/NewMessageView.swift
- MailCore/Models/Draft.swift
- MailCore/Models/Signature.swift
> Use signature when composing email

- MailCore/Cache/MailboxManager.swift
> Update the number of unreads after moving or deleting a message

- Mail/Views/Menu Drawer/Folders/FolderCell.swift
> Use a live object when switching folder

- Mail/Views/Thread/MessageHeaderView.swift
> Bottom sheet of a message: "Mark as read" not updated

- Mail/Views/Thread/ThreadView.swift
> Fix thread view slow

- Mail/Views/Thread List/ThreadListView.swift
- Mail/Views/Thread List/ThreadListViewModel.swift
- Mail/Views/Thread/ThreadView.swift
- MailCore/Models/Thread.swift
> Update unread toggle

- Mail/Helpers/RichTextEditor.swift
- Mail/Views/New Message/NewMessageView.swift
- MailCore/Cache/MailboxManager.swift
- MailCore/Models/Draft.swift
- MailCore/Models/Signature.swift
> Fix Drafts

- Mail/Views/Thread List/ThreadListView.swift
Fix force refresh with EmptyView
Fix progress not showing
Remove useless background
> Small fixes ProgressView / ZStack / Empty

- Mail/Components/FloatingActionButton.swift
- Mail/Views/Thread List/EmptyListView.swift
- Mail/Views/Thread List/ThreadListView.swift
- Mail/Views/ThreadListManagerView.swift
- MailCore/Utils/Constants.swift
Fix alignment + Background empty view dark mode
> Fix centering / background empty view

- Mail/Views/Settings/Other Settings/GeneralSettingsViewModel.swift
- Mail/Views/Settings/SettingsOptionView.swift
- Mail/Views/Settings/SettingsSwipeActionsView.swift
- Mail/Views/Settings/SettingsView.swift
- Mail/Views/Settings/SkeletonSwipeCell.swift
- Mail/Views/Settings/SwipeConfigCell.swift
> Fix: Settings layout

- Mail/Views/Search/SearchView.swift
- Mail/Views/Thread List/ThreadListCell.swift
- Mail/Views/Thread/ThreadView.swift
- Mail/Views/ThreadListManagerView.swift
> Refactor: Stop passing folderId and trashFolderId to ThreadView

- Mail/Views/Thread List/ThreadListView.swift
- Mail/Views/Thread List/ThreadListViewModel.swift
- MailCore/Cache/MailboxManager.swift
Fix a crash when leaving the searchView.
Fix a crash where a thread is empty if this same thread was searched in the searchView.
> Empty mail

- Mail/Views/Bottom sheets/Actions/ActionsViewModel.swift
- Mail/Views/Thread List/ThreadListCell.swift
- Mail/Views/Thread List/ThreadListMultipleSectionViewModel.swift
- Mail/Views/Thread List/ThreadListView.swift
> Haptic feedback

- .package.resolved
- Mail/Views/LottieView.swift
- Mail/Views/Onboarding/IlluColors.swift
- Mail/Views/Onboarding/LottieView.swift
- Mail/Views/Onboarding/OnboardingView.swift
- Mail/Views/Onboarding/SlideView.swift
- Project.swift
> Change color illustration

- MailCore/API/Endpoint.swift
- MailCore/API/MailApiFetcher.swift
- MailCore/Cache/MailboxManager.swift
- MailCore/Utils/Constants.swift
Now get 500 first messages during folder first launch
> feat: Folder first launch

- Mail/Utils/NetworkMonitor.swift
- Mail/Views/SplitView.swift
- Mail/Views/Thread List/ThreadListView.swift
Stop flickering when changing folder
+ Update threads when changing folder
> fix(iPad): Flickering when changing folder

- Mail/Components/IndeterminateProgressView.swift
- Mail/Views/New Message/AttachmentsHeaderView.swift
- Mail/Views/New Message/AttachmentsManager.swift
- Mail/Views/New Message/ComposeMessageView.swift
- Mail/Views/Thread/AttachmentCell.swift
- MailCore/API/MailApiFetcher.swift
- MailCore/Models/Attachment.swift
- Basic error handling
- Upload progress tracking
> Attachments improvements

- Mail/Views/New Message/Attachments/AttachmentsManager.swift
> Attachments cancel upload task

- Mail/Components/ThreadCell.swift
- Mail/Views/Search/SearchView.swift
- Mail/Views/Thread List/ThreadListCell.swift
- Mail/Views/Thread List/ThreadListView.swift
- MailCore/Models/Recipient.swift
- MailCore/Models/Thread.swift
- Display list of recipients on ThreadCell (e.g. "Elena, Philippe, Ambroise, Adrien)
- Display last message from folder and not from thread
> fix(ThreadCell):  Display data correctly

- Mail/Views/Bottom sheets/BottomSheetButtonsView.swift
- Mail/Views/New Message/Attachments/AttachmentsHeaderView.swift
- Mail/Views/New Message/Attachments/AttachmentsManager.swift
- Mail/Views/New Message/Attachments/AttachmentsUploadInProgressErrorView.swift
- Mail/Views/New Message/ComposeMessageView.swift
- MailCore/API/MailError.swift
- MailCore/Utils/Constants.swift
> feat: Attachment global errors

- Mail/Components/RecipientField.swift
- Mail/Components/ThreadCell.swift
- Mail/Utils/FilterCellModifier.swift
- Mail/Views/Menu Drawer/MailboxQuotaView.swift
- Mail/Views/Search/SearchView.swift
- MailCore/Utils/MailTextStyle.swift
> refactor: Accent Color

- Mail/Views/Thread/MessageListView.swift
- Mail/Views/Thread/ThreadView.swift
Remove computed property to correctly observe list
> fix(MessageListView): Fix message list not updating after deleting draft

- MailCore/API/MailApiFetcher.swift
- MailCore/Cache/ContactManager.swift
- MailCore/Models/Contact.swift
- MailCore/Models/MergedContact.swift
- Contact names are now optional
- Send to sentry bad json
> fix: Improve decoding

- Mail/Views/New Message/ComposeMessageView.swift
> fix(ComposeMessageView): Enable button when to/cc/bcc is filled

- Mail/Components/ModalButton.swift
- Mail/Components/ModalButtonsView.swift
- Mail/Views/AlertView.swift
- Mail/Views/Alerts/AddLinkView.swift
- Mail/Views/Alerts/CreateFolderView.swift
- Mail/Views/Alerts/LogoutConfirmationView.swift
- Mail/Views/Alerts/ReportPhishingView.swift
- Mail/Views/Bottom sheets/MoreStorageView.swift
- Mail/Views/Bottom sheets/ReportDisplayProblemView.swift
- Mail/Views/Bottom sheets/RestoreEmailsView.swift
- Mail/Views/New Message/Attachments/AttachmentsHeaderView.swift
- Mail/Views/New Message/Attachments/AttachmentsUploadInProgressErrorView.swift
- Mail/Views/New Message/ComposeMessageView.swift
- Mail/Views/SheetView.swift
- Mail/Views/SplitView.swift
- Mail/Views/Switch User/AccountView.swift
- Mail/Views/Thread List/FlushFolderAlertView.swift
> refactor: Dismiss modal with environment variable

- Mail/Components/CheckboxView.swift
- Mail/Components/ThreadCell.swift
- Mail/Components/ThreadCellDetailsView.swift
- Mail/Components/ThreadCellHeaderView.swift
- Mail/Components/ThreadCellInfoView.swift
- Mail/Components/UnreadIndicatorView.swift
- MailCore/Models/Recipient.swift
Multiple performance improvements around thread cell
> perf: Improve ThreadCell redraws

- .package.resolved
- MailCore/API/MailApiFetcher.swift
- MailCore/Cache/BackgroundRealm.swift
> chore: Upgrade sentry

- Mail/Components/SelectionBackground.swift
- Mail/Components/ThreadCell.swift
- Mail/Views/Bottom sheets/Actions/ActionsView.swift
- Mail/Views/Bottom sheets/Actions/ActionsViewModel.swift
- Mail/Views/New Message/Attachments/AttachmentUploadCell.swift
- Mail/Views/Thread List/ThreadListCell.swift
- Mail/Views/Thread List/ThreadListMultipleSectionViewModel.swift
- Mail/Views/Thread List/ThreadListView.swift
- Mail/Views/Thread List/ThreadListViewModel.swift
> feat: Update multiple selection behavior

- Mail/Views/Thread List/ThreadListViewModel.swift
- MailCore/Models/Thread.swift
> perf: Remove useless filter + Sort in background

- MailCore/Utils/LocalContactsHelper.swift
-> CNContactOrganizationNameKey
> fix(LocalContactsHelper): Stop fetching useless contact key

- Mail/Utils/AppShadowModifier.swift
> fix(AppShadowModifier): Prevent breaking view identity 

- MailCore/Models/CancelableResponse.swift
For now we don't handle delay > 0
> fix: Remove cancelResource for SendResponse

- Mail/Views/SplitView.swift
> fix(SplitView): Remove always twoDisplaceSecondary

- Mail/Helpers/RichTextEditor.swift
- Mail/Views/New Message/ComposeMessageView.swift
Reply / Reply all focus on the editor
> fix: Reply to/all focus on the editor

- Mail/Components/RecipientField.swift
- Mail/Views/New Message/ComposeMessageView.swift
- If the email is not in contacts but valid, we try to use it.
> Keyboard select best match on enter

- Mail/Views/Menu Drawer/MenuHeaderView.swift
~ Here is a before and after. Out with the old and in with the new ✨
> feat: settings button with a nice touchable zone

- Mail/Views/New Message/ComposeMessageView.swift
Error appears when closing the view
> fix(ComposeMessageView): Prevent modifying state error

- Mail/Views/New Message/ComposeMessageBodyView.swift
> fix: Insert signature after mailto body

- Mail/Views/Thread/WebView.swift
Like asked by @valentinperignon I call `webView.evaluateJavaScript("listenToSizeChanges()"` earlier. It did fix the issue.
> fix Message not loading on invalid URL

- Mail/Components/SearchTextField.swift
And also provide a "search" button to close keyboard
> fix: Open keyboard search on appear

- MailCore/Cache/ContactManager.swift
> feat(ContactManager): Try to match email address then name when matching contact

- MailCore/API/MailApiFetcher.swift
- MailCore/Cache/AccountManager.swift
> refactor: Simplify refresh token

- MailCore/Cache/MailboxManager.swift
- MailCore/Cache/RefreshActor.swift
Fix by putting `refreshFolder(from messages)` function into an actor for locking.
> Fix archive UI glitch

- MailNotificationServiceExtension/NotificationServiceAssembly.swift
> fix(DI): Missing type in shareExtension

- Tuist/ProjectDescriptionHelpers/Constants.swift
1.0.6-1 reference build. Same as a 1.0.5-7.
> bump to 1.0.6

- MailCore/Cache/BackgroundExecutor.swift
- MailCore/Utils/TolerantDispatchGroup.swift
Ensure we balance calls to prevent crashing on DispatchGroup leave.
> fix: TolerantDispatchGroup

- Mail/Views/AI Writer/AIProgressView.swift
- Mail/Views/AI Writer/AIPromptView.swift
- Mail/Views/New Message/ComposeMessageView.swift
- MailCore/API/Endpoint.swift
- MailCore/API/MailApiFetcher/MailApiFetcher+AI.swift
- MailCore/Models/AIMessage.swift
- MailCore/Utils/MailTextStyle.swift
- MailResources/Localizable/de.lproj/Localizable.strings
- MailResources/Localizable/en.lproj/Localizable.strings
- MailResources/Localizable/es.lproj/Localizable.strings
- MailResources/Localizable/fr.lproj/Localizable.strings
- MailResources/Localizable/it.lproj/Localizable.strings
> feat(AI Writer): API call

- Mail/Views/Thread List/ThreadListViewModel+Observation.swift
While we wait to see if the issue can be resolved on Realm's end (https://github.com/realm/realm-core/issues/7056). We resort to sectioning by ourselves.
> fix: Prevent realm crash while sectioning

- .package.resolved
- Mail/Components/InformationBlockView.swift
- Mail/Views/AI Writer/AIDismissibleErrorView.swift
- Matomo event (User dismiss error)
- Align error icon with message
> feat(AIWriter): Error UI improvements

- Mail/MailApp.swift
- Mail/Views/Alerts/AskForReviewView.swift
- Mail/Views/New Message/ComposeMessageView.swift
- Mail/Views/SplitView.swift
- MailCore/Cache/ReviewManager.swift
- MailCore/Utils/Constants.swift
- MailCore/Utils/MailUserDefaults+Extension.swift
> feat(Review): Ask user for rating

- Mail/Views/Alerts/AskForReviewView.swift
- MailCore/Utils/Matomo+Extension.swift
> feat(MatomoUtils): Add Review events

- Mail/Views/Menu Drawer/Items/MenuDrawerItemCell.swift
- Mail/Views/Menu Drawer/Items/MenuDrawerItemsListView.swift
- Mail/Views/Settings/General/SettingsView.swift
- Mail/Views/Sync Profile/SyncWelcomeView.swift
- MailResources/Localizable/de.lproj/Localizable.strings
- MailResources/Localizable/en.lproj/Localizable.strings
- MailResources/Localizable/es.lproj/Localizable.strings
- MailResources/Localizable/fr.lproj/Localizable.strings
- MailResources/Localizable/it.lproj/Localizable.strings
Waiting for @PhilippeWeidmann.
> fix(Sync): Update wordings

- MailCore/API/MailApiFetcher/MailApiFetchable.swift
- MailCore/API/MailApiFetcher/MailApiFetcher+Extended.swift
- MailCore/Utils/FeatureFlagsManageable.swift
- MailCore/Utils/FeatureFlagsManager.swift
~Waiting for confirmation on `email` instead of `mailboxId`~
> fix: Feature flags are now per mailbox

- Mail/RootView.swift
- Mail/Views/EmptyStateView.swift
- Mail/Views/Menu Drawer/FolderListView.swift
- Mail/Views/Menu Drawer/Folders/FolderCell.swift
- Mail/Views/Menu Drawer/Folders/FoldersListView.swift
- Mail/Views/SplitView.swift
- Mail/Views/ThreadListManagerView.swift
- MailCore/Cache/MainViewState.swift
- MailCore/Cache/NavigationState.swift
> feat: Non optional selected folder

- Mail/Components/ThreadCell.swift
- Mail/Components/ThreadCellHeaderView.swift
- Mail/Helpers/PreviewHelper.swift
It is more correct and allegedly more performant
> fix(ThreadCell): Use frame instead of Spacer

- Mail/Components/AvatarView.swift
- MailCore/Models/Contact/ContactConfiguration.swift
- MailCore/ViewModel/AvatarViewModel.swift
To resolve Sentry `MAIL-IOS-5D1`
> fix: Freeze ContactConfiguration before sending to AvatarLoader

- .package.resolved
- Tuist/ProjectDescriptionHelpers/Constants.swift
> chore: 1.0.13

- Mail/Views/Menu Drawer/MenuHeaderView.swift
- Mail/Views/Settings/SettingsNavigationView.swift
- Mail/Views/Settings/SettingsSubMenuCell.swift
- Mail/Views/Settings/SettingsView.swift
- Mail/Views/SplitView.swift
- MailCore/Cache/MainViewState.swift
- MailCore/Cache/SettingsDestination.swift
For now this only handled notifications deeplinking. However, other sections / view can easily be handled using deeplinking.
> feat: Settings improved navigation

- Mail/Helpers/Notifications/NotificationCenterDelegate.swift
- Mail/Views/Settings/General/SettingsNotificationsView.swift
- Mail/Views/SplitView.swift
- MailCore/Utils/Notification+Name.swift
> feat: Deep linking notifications

- MailCore/Cache/MailboxManager/MailboxManager+Message.swift
It should be okay to delete orphans. This is also aligned with what Android team is doing.
> fix: Delete orphan messages

- MailCore/Cache/ContactManager/ContactManager+DB.swift
> fix: Use slicing instead of iterator

- Mail/Views/New Message/ComposeMessageView.swift
- Mail/Views/New Message/ExternalTagBottomView.swift
- Mail/Views/Thread/ThreadView.swift
- MailCore/Utils/Model/DisplayExternalRecipientStatus.swift
> refactor(ComposeView): Remove composeView property

- Mail/Commands/CustomCommands.swift
- Mail/Commands/MessageCommands.swift
- Mail/Commands/NewMessageCommand.swift
- Mail/Commands/OpenSettingsCommand.swift
- Mail/Commands/PrintMessageCommand.swift
- Mail/UserAccountScene.swift
- MailCore/Models/Draft.swift
- MailCore/Utils/Matomo+Extension.swift
- MailResources/Localizable/de.lproj/Localizable.strings
- MailResources/Localizable/en.lproj/Localizable.strings
- MailResources/Localizable/es.lproj/Localizable.strings
- MailResources/Localizable/fr.lproj/Localizable.strings
- MailResources/Localizable/it.lproj/Localizable.strings
- MailResources/Mail.entitlements
> feat: Command bar on macOS

- Mail/Views/Thread/Message/MessageHeader/MessageHeaderDateView.swift
- Mail/Views/Thread/Message/MessageHeader/MessageHeaderSummaryView.swift
- Mail/Views/Thread/Message/MessageHeader/MessageHeaderView.swift
- Mail/Views/Thread/Message/MessageView.swift
- MailCore/Utils/Formatters.swift
messageHeaderRelativeFormatted and customRelativeFormatted will be refactored to use `FormatStyle` in next PR for readability
> feat: Add time threadview

- MailCore/Cache/MailboxManager/MailboxManager+Thread.swift
Fix prevent deleting mid-flight drafts
> fix: Prevent race condition when updating messages and drafts

- MailCore/Cache/MailboxManager/MailboxManager+Thread.swift
First problem detected by sentry and metrickit 🎉  (MAIL-IOS-HAX)
> perf: Use lazy where first instead of non lazy first where

- MailCore/Cache/MailboxManager/MailboxManager+Local.swift
- MailCore/Cache/MailboxManager/MailboxManager+Message.swift
- MailCore/Cache/MailboxManager/MailboxManager+Thread.swift
Read/Unread + Star/Unstar message before making the API call
> feat: Fast action before API call

- Mail/Views/Thread List/FlushFolderView.swift
> fix: Fix incorrect folder passed

- MailUITests/MailUITests.swift
> test: Test create folder

- Mail/Views/New Message/ExternalTagBottomView.swift
| Before | After |
|--------|------|
| ![before](https://github.com/Infomaniak/ios-kMail/assets/25110022/b8696668-aa73-4d2f-bcbf-33995b6202e0)|![after](https://github.com/Infomaniak/ios-kMail/assets/25110022/92a8f511-9f4c-4d48-9201-d8f4188084cc)|
> feat(ExternalTagBottomView): Move info icon to the leading side

- MailCore/API/SyncedAuthenticator.swift
- MailCore/Utils/Logging.swift
- MailCore/Utils/SentryDebug.swift
Now tracking old and new token during an update to track further issues.
Drive PR https://github.com/Infomaniak/ios-kDrive/pull/1201
> fix: Emit a Sentry event on Token auth error

- MailCore/Cache/Actions/ActionsManager.swift
- MailCore/Cache/MailboxManager/MailboxManager+Message.swift
- MailCore/Utils/SnackBar/IKSnackBar+Extension.swift
- MailCore/Utils/UndoAction.swift
(The tests were done using network link conditioner in 2G to really show the difference)
Before:  
https://github.com/Infomaniak/ios-kMail/assets/5843044/176cf089-e0b5-4439-bf72-284d7ef77ca4
After: 
https://github.com/Infomaniak/ios-kMail/assets/5843044/ba802627-4370-484d-82b4-80a04b259d6e
> feat: Instant snackbar on move and delete

- Mail/Views/Thread/Message/MessageHeader/MessageHeaderSummaryView.swift
Improve accessibility and focus on macOS for Full Keyboard Access users.
- Enable message expansion
> feat: Improve accessibility on macOS

- MailNotificationServiceExtension/NotificationService.swift
> fix: Notification body displays key instead of trad

- Mail/Components/ThreadCell/ThreadCell.swift
- Mail/Components/ThreadCell/ThreadCellBodyView.swift
- Mail/Components/ThreadCell/ThreadCellTextView.swift
**Description:**
In the spam folder display the email inside angle brackets <> in the ThreadListCell
**Spam folder:**
**Others folders:**
> feat: Display email in ThreadListCell if folder is spam

- Mail/Utils/ShortcutModifier.swift
- Mail/Views/Search/SearchModifiers.swift
- Mail/Views/Search/SearchThreadsSectionView.swift
- Mail/Views/Search/SearchViewModel+Observation.swift
- Mail/Views/Thread List/MultipleSectionViewModel.swift
- Mail/Views/Thread List/ThreadListModifiers.swift
- Mail/Views/Thread List/ThreadListView.swift
- Add selectAll button on search multi selection
- fix: Get next page on search wasn't working
- fix: Keep multi selected threads selected on reload / next page
> fix: Select all on search

- Mail/Components/Custom Buttons/LoadMoreButton.swift
- MailCore/API/Endpoint.swift
- MailCore/API/MailApiFetcher/MailApiFetchable.swift
- MailCore/API/MailApiFetcher/MailApiFetcher+Extended.swift
- MailCore/API/MailError.swift
- MailCore/Cache/MailboxManager/MailboxManageable.swift
- MailCore/Cache/MailboxManager/MailboxManager+Thread.swift
- MailCore/Cache/MailboxManager/MailboxManager.swift
- MailCore/Models/Folder.swift
- MailCore/Models/Message.swift
- MailCore/Utils/Constants.swift
- MailCore/Utils/SentryDebug.swift
- MailTests/Folders/ITFolderListViewModel.swift
- MailTests/Search/ITSearchViewModel.swift
- New way to get old messages
- Get new messages using Delta
> feat: Thread algo updated

- Mail/Views/Search/SearchModifiers.swift
- Mail/Views/Thread List/ThreadListModifiers.swift
- Mail/Views/Thread/ThreadView.swift
- MailCoreUI/Components/BottomBarView.swift
- MailCoreUI/Components/ToolbarButton.swift
- Simplify BottomBarView 
- Remove Spacer()
> refactor: Remove Spacer() from BottomBarView

- Mail/Views/New Message/ComposeMessageProgressView.swift
- Mail/Views/New Message/ComposeMessageToolbarModifier.swift
- Mail/Views/New Message/ComposeMessageView.swift
Attempt to make a unique toolbar for Compose Message view
> style: Unique toolbar for compose message view

- Mail/Views/New Message/Select Mailbox/CurrentComposeMailboxView.swift
- Mail/Views/New Message/Select Mailbox/SelectComposeMailboxView.swift
- Mail/Views/New Message/Select Mailbox/SelectComposeMailboxViewModel.swift
> refactor: Use UserProfile instead of Account

- Mail/Views/New Message/ComposeMessageToolbarModifier.swift
- Mail/Views/New Message/Select Mailbox/CurrentComposeMailboxView.swift
- Mail/Views/Settings/SettingsNavigationView.swift
- Mail/Views/SplitView.swift
- MailCore/Utils/PlatformDetectable+Extension.swift
Also added some way to close some sheets on macOS 12
> fix: Pass forward env to prevent crash on macOS 12

- Tuist/Package.resolved
- Tuist/Package.swift
This impact on Mail (unlike drive) should be nil. I tested login / logout / read mail without issues.
> chore: Bump ios-core

- MailCore/API/Endpoint.swift
- MailCore/API/MailApiFetcher/MailApiFetchable.swift
- MailCore/API/MailApiFetcher/MailApiFetcher+Extended.swift
- MailCore/Cache/MailboxManager/MailboxManager+Thread.swift
- MailCore/Models/Folder.swift
- MailCore/Models/MessagesDelta.swift
- MailCore/Utils/Constants.swift
Depends on #1676 
Depends on Infomaniak/ios-core#1
> feat(Snooze): Fetch messages from SNOOZED folder

- Mail/Views/Search/SearchViewModel.swift
Handle the first loading without saying No result
> fix: Loading by default

- MailCore/API/MailApiError.swift
- MailCore/Models/EmojiReactionNotAllowedReason.swift
- MailResources/Localizable/de.lproj/Localizable.strings
- MailResources/Localizable/en.lproj/Localizable.strings
- MailResources/Localizable/es.lproj/Localizable.strings
- MailResources/Localizable/fr.lproj/Localizable.strings
- MailResources/Localizable/it.lproj/Localizable.strings
> feat(EmojiReaction): Handle errors

- MailResources/Localizable/de.lproj/Localizable.stringsdict
- MailResources/Localizable/en.lproj/Localizable.stringsdict
- MailResources/Localizable/es.lproj/Localizable.stringsdict
- MailResources/Localizable/fr.lproj/Localizable.stringsdict
- MailResources/Localizable/it.lproj/Localizable.stringsdict
Quick fix to rename to be more consistent with reality.
> chore: Reword message to conversation

- MailCore/Models/Thread.swift
> feat: Order reactions by message date

- TestFlight/WhatToTest.en-GB.txt
- TestFlight/WhatToTest.fr-FR.txt
- Tuist/Package.resolved
- Tuist/ProjectDescriptionHelpers/Constants.swift
I'll open this for review as soon as I get QA's go.
> chore: Release build 1.5.1

- .mise.toml
- .swiftlint.yml
- Mail/Components/ThreadCell/ThreadCellTextView.swift
- Mail/Helpers/Notifications/NotificationCenterDelegate.swift
- Mail/Utils/DraftUtils.swift
- Mail/Views/Alerts/ExternalRecipientView.swift
- Mail/Views/Bottom sheets/Actions/ContactActionsView/ContactActionsHeaderView.swift
- Mail/Views/New Message/ComposeMessageView.swift
- Mail/Views/Search/SearchFilterCell.swift
- Mail/Views/Search/SearchFilterFolderCell.swift
- Mail/Views/Search/SearchViewModel.swift
- Mail/Views/Thread/Message/BodyImageProcessor.swift
- MailCore/Models/Body.swift
- MailCoreUI/Components/RecipientChip/EncryptedChipAccessoryUIView.swift
- MailShareExtension/ShareViewController.swift
- Upgrade dev tools
- Remove redundant public using new SwiftFormat
- SwiftLint config now uses include instead of exclude -> Linting took 7 sec before and now takes 0.5 sec
> chore: Upgrade dev tools + SwiftLint config changes

- Mail/Views/Attachment/AttachmentPreview.swift
- Mail/Views/Encryption/EncryptionPasswordView.swift
- Mail/Views/New Message/ComposeMessageToolbarModifier.swift
- Mail/Views/New Message/ComposeMessageView.swift
- Mail/Views/New Message/Select Mailbox/CurrentComposeMailboxView.swift
- Mail/Views/Settings/SettingsNavigationView.swift
- Mail/Views/Sync Profile/SyncProfileNavigationView.swift
- Mail/Views/Thread/ThreadTitleModifier.swift
- Mail/Views/Thread/ThreadView.swift
- Mail/Views/Thread/WebView/ThreadViewToolbarModifier.swift
- MailCoreUI/Components/CloseButton.swift
- MailCoreUI/Extensions/View+Extension.swift
- MailCoreUI/ViewModifier/SheetViewModifier.swift
- Tuist/Package.resolved
- Tuist/Package.swift
> feat(iOS 26): Update navbars
